#pragma once

#define GSH_VULKAN_FLAVOR_DESKTOP 0
#define GSH_VULKAN_FLAVOR_MOBILE 1

#ifdef __ANDROID__
#define GSH_VULKAN_FLAVOR GSH_VULKAN_FLAVOR_MOBILE
#else
#define GSH_VULKAN_FLAVOR GSH_VULKAN_FLAVOR_DESKTOP
#endif

#define GSH_VULKAN_IS_DESKTOP (GSH_VULKAN_FLAVOR == GSH_VULKAN_FLAVOR_DESKTOP)
#define GSH_VULKAN_IS_MOBILE (GSH_VULKAN_FLAVOR == GSH_VULKAN_FLAVOR_MOBILE)

#if !GSH_VULKAN_IS_DESKTOP && !GSH_VULKAN_IS_MOBILE
#error Unknown Vulkan flavor.
#endif
