//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ElfViewRes.rc
//
#define IDD_ELFVIEW_HEADERVIEW          2000
#define IDC_ELFVIEW_HEADERVIEW_TYPE_EDIT 2000
#define IDC_ELFVIEW_HEADERVIEW_MACHINE_EDIT 2001
#define IDD_ELFVIEW_PROGRAMVIEW         2001
#define IDC_ELFVIEW_HEADERVIEW_VERSION_EDIT 2002
#define IDD_ELFVIEW_SECTIONVIEW         2002
#define IDC_ELFVIEW_HEADERVIEW_TYPE_LABEL 2003
#define IDC_ELFVIEW_HEADERVIEW_VERSION_LABEL 2004
#define IDC_ELFVIEW_HEADERVIEW_MACHINE_LABEL 2005
#define IDC_ELFVIEW_HEADERVIEW_SHSTRTAB_EDIT 2006
#define IDC_ELFVIEW_PROGRAMVIEW_TYPE_LABEL 2006
#define IDC_ELFVIEW_HEADERVIEW_SHSTRTAB_LABEL 2007
#define IDC_ELFVIEW_PROGRAMVIEW_TYPE_EDIT 2007
#define IDC_ELFVIEW_HEADERVIEW_FLAGS_EDIT 2008
#define IDC_ELFVIEW_PROGRAMVIEW_OFFSET_EDIT 2008
#define IDC_ELFVIEW_SECTIONVIEW_TYPE_LABEL 2008
#define IDC_ELFVIEW_HEADERVIEW_FLAGS_LABEL 2009
#define IDC_ELFVIEW_PROGRAMVIEW_OFFSET_LABEL 2009
#define IDC_ELFVIEW_SECTIONVIEW_TYPE_EDIT 2009
#define IDC_ELFVIEW_HEADERVIEW_ENTRY_EDIT 2010
#define IDC_ELFVIEW_SECTIONVIEW_FLAGS_EDIT 2010
#define IDC_ELFVIEW_HEADERVIEW_ENTRY_LABEL 2011
#define IDC_ELFVIEW_SECTIONVIEW_FLAGS_LABEL 2011
#define IDC_ELFVIEW_HEADERVIEW_SIZE_EDIT 2012
#define IDC_ELFVIEW_PROGRAMVIEW_VADDR_EDIT 2012
#define IDC_ELFVIEW_SECTIONVIEW_ADDRESS_EDIT 2012
#define IDC_ELFVIEW_HEADERVIEW_SIZE_LABEL 2013
#define IDC_ELFVIEW_PROGRAMVIEW_VADDR_LABEL 2013
#define IDC_ELFVIEW_SECTIONVIEW_ADDRESS_LABEL 2013
#define IDC_ELFVIEW_HEADERVIEW_PHOFFSET_EDIT 2014
#define IDC_ELFVIEW_SECTIONVIEW_OFFSET_EDIT 2014
#define IDC_ELFVIEW_HEADERVIEW_PHOFFSET_LABEL 2015
#define IDC_ELFVIEW_SECTIONVIEW_OFFSET_LABEL 2015
#define IDC_ELFVIEW_HEADERVIEW_PHSIZE_EDIT 2016
#define IDC_ELFVIEW_PROGRAMVIEW_PADDR_EDIT 2016
#define IDC_ELFVIEW_SECTIONVIEW_SIZE_EDIT 2016
#define IDC_ELFVIEW_HEADERVIEW_PHSIZE_LABEL 2017
#define IDC_ELFVIEW_PROGRAMVIEW_PADDR_LABEL 2017
#define IDC_ELFVIEW_SECTIONVIEW_SIZE_LABEL 2017
#define IDC_ELFVIEW_HEADERVIEW_PHCOUNT_EDIT 2018
#define IDC_ELFVIEW_PROGRAMVIEW_FILESIZE_EDIT 2018
#define IDC_ELFVIEW_SECTIONVIEW_LINK_EDIT 2018
#define IDC_ELFVIEW_HEADERVIEW_PHCOUNT_LABEL 2019
#define IDC_ELFVIEW_PROGRAMVIEW_FILESIZE_LABEL 2019
#define IDC_ELFVIEW_SECTIONVIEW_LINK_LABEL 2019
#define IDC_ELFVIEW_HEADERVIEW_SHOFFSET_EDIT 2020
#define IDC_ELFVIEW_PROGRAMVIEW_MEMSIZE_EDIT 2020
#define IDC_ELFVIEW_SECTIONVIEW_INFO_EDIT 2020
#define IDC_ELFVIEW_HEADERVIEW_SHOFFSET_LABEL 2021
#define IDC_ELFVIEW_PROGRAMVIEW_MEMSIZE_LABEL 2021
#define IDC_ELFVIEW_SECTIONVIEW_INFO_LABEL 2021
#define IDC_ELFVIEW_HEADERVIEW_SHSIZE_EDIT 2022
#define IDC_ELFVIEW_PROGRAMVIEW_FLAGS_EDIT 2022
#define IDC_ELFVIEW_SECTIONVIEW_ALIGN_EDIT 2022
#define IDC_ELFVIEW_HEADERVIEW_SHSIZE_LABEL 2023
#define IDC_ELFVIEW_PROGRAMVIEW_FLAGS_LABEL 2023
#define IDC_ELFVIEW_SECTIONVIEW_ALIGN_LABEL 2023
#define IDC_ELFVIEW_HEADERVIEW_SHCOUNT_EDIT 2024
#define IDC_ELFVIEW_PROGRAMVIEW_ALIGN_EDIT 2024
#define IDC_ELFVIEW_SECTIONVIEW_ENTRYSIZE_EDIT 2024
#define IDC_ELFVIEW_HEADERVIEW_SHCOUNT_LABEL 2025
#define IDC_ELFVIEW_PROGRAMVIEW_ALIGN_LABEL 2025
#define IDC_ELFVIEW_SECTIONVIEW_ENTRYSIZE_LABEL 2025
#define IDC_ELFVIEW_SECTIONVIEW_CONTENTS_PLACEHOLDER 2026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2003
#define _APS_NEXT_COMMAND_VALUE         42000
#define _APS_NEXT_CONTROL_VALUE         2027
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
