#pragma once

#define PREFERENCE_UI_SHOWFPS "ui.showfps"
#define PREFERENCE_UI_SHOWVIRTUALPAD "ui.showvirtualpad"

#define PREFERENCE_AUDIO_ENABLEOUTPUT "audio.enableoutput"

#define PREFERENCE_VIDEO_GS_HANDLER "video.gshandler"

#define PREFERENCE_VALUE_VIDEO_GS_HANDLER_OPENGL 0
#define PREFERENCE_VALUE_VIDEO_GS_HANDLER_VULKAN 1
