name: Build Linux ARM32

on: [push, pull_request]
jobs:
  build_linux_arm32:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install qemu-user-static binfmt-support
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build & Test
        uses: addnab/docker-run-action@v2
        with:
          image: jpd002/linux_arm32_build
          options: -v ${{ github.workspace }}:/work
          run: |
            set -e
            apt-get update
            apt-get install -y libcurl4-openssl-dev libgl1-mesa-dev libglu1-mesa-dev libalut-dev libevdev-dev qt6-base-dev
            cd /work
            cd build_cmake
            mkdir build
            cd build
            cmake ../..
            make -j $(nproc)
            # VuTest won't work on ARMv7 due to FP differences
            ctest -C Release -E "(VuTest)"
